version: "3"

networks:
  tellee-base-net:
    driver: bridge

volumes:
  tellee-users-db-volume:
  tellee-things-db-volume:
  tellee-mqtt-redis-volume:
  tellee-things-redis-volume:
  tellee-es-redis-volume:
  tellee-bootstrap-db-volume:
  tellee-influxdb-volume:

services:
  nginx:
    image: nginx:1.14.2
    container_name: tellee-nginx
    restart: on-failure
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf
      - ./ssl/authorization.js:/etc/nginx/authorization.js
      - ./ssl/certs/tellee-server.crt:/etc/ssl/certs/tellee-server.crt
      - ./ssl/certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./ssl/certs/tellee-server.key:/etc/ssl/private/tellee-server.key
      - ./ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
      - 8883:8883
    networks:
      - tellee-base-net

  nats:
    image: nats:1.3.0
    container_name: tellee-nats
    restart: on-failure
    networks:
      - tellee-base-net

  users-db:
    image: postgres:10.2-alpine
    container_name: tellee-users-db
    restart: on-failure
    environment:
      POSTGRES_USER: tellee
      POSTGRES_PASSWORD: tellee
      POSTGRES_DB: users
    ports:
      - 5432:5432
    networks:
      - tellee-base-net
    volumes:
      - tellee-users-db-volume:/var/lib/postgresql/data

  users:
    image: rkrikbaev/users:0.8.0
    container_name: tellee-users
    depends_on:
      - users-db
    expose:
      - 8181
    restart: on-failure
    environment:
      MF_USERS_LOG_LEVEL: debug
      MF_USERS_DB_HOST: users-db
      MF_USERS_DB_PORT: 5432
      MF_USERS_DB_USER: tellee
      MF_USERS_DB_PASS: tellee
      MF_USERS_DB: users
      MF_USERS_HTTP_PORT: 8180
      MF_USERS_GRPC_PORT: 8181
      MF_USERS_SECRET: secret
    ports:
      - 8180:8180
    networks:
      - tellee-base-net

  things-db:
    image: postgres:10.2-alpine
    container_name: tellee-things-db
    restart: on-failure
    environment:
      POSTGRES_USER: tellee
      POSTGRES_PASSWORD: tellee
      POSTGRES_DB: things
    networks:
      - tellee-base-net
    volumes:
      - tellee-things-db-volume:/var/lib/postgresql/data

  things-redis:
    image: redis:5.0-alpine
    container_name: tellee-things-redis
    restart: on-failure
    networks:
      - tellee-base-net
    volumes:
      - tellee-things-redis-volume:/data

  things:
    image: rkrikbaev/things:0.8.0
    container_name: tellee-things
    depends_on:
      - things-db
      - users
    restart: on-failure
    environment:
      MF_THINGS_LOG_LEVEL: debug
      MF_THINGS_DB_HOST: things-db
      MF_THINGS_DB_PORT: 5432
      MF_THINGS_DB_USER: tellee
      MF_THINGS_DB_PASS: tellee
      MF_THINGS_DB: things
      MF_THINGS_CACHE_URL: things-redis:6379
      MF_THINGS_ES_URL: es-redis:6379
      MF_THINGS_HTTP_PORT: 8182
      MF_THINGS_GRPC_PORT: 8183
      MF_USERS_URL: users:8181
      MF_THINGS_SECRET: secret
    ports:
      - 8182:8182
      - 8183:8183
    networks:
      - tellee-base-net

  normalizer:
    image: rkrikbaev/normalizer:0.8.0
    container_name: tellee-normalizer
    restart: on-failure
    depends_on:
      - nats
    expose:
      - 8184
    environment:
      MF_NORMALIZER_LOG_LEVEL: debug
      MF_NATS_URL: nats://nats:4222
      MF_NORMALIZER_PORT: 8184
    ports:
      - 8184:8184
    networks:
      - tellee-base-net

  ws-adapter:
    image: rkrikbaev/ws:0.8.0
    container_name: tellee-ws
    depends_on:
      - things
      - nats
    restart: on-failure
    environment:
      MF_WS_ADAPTER_LOG_LEVEL: debug
      MF_WS_ADAPTER_PORT: 8186
      MF_NATS_URL: nats://nats:4222
      MF_THINGS_URL: things:8183
    ports:
      - 8186:8186
    networks:
      - tellee-base-net

  http-adapter:
    image: rkrikbaev/http:0.8.0
    container_name: tellee-http
    depends_on:
      - things
      - nats
    restart: on-failure
    expose:
      - 8185
    environment:
      MF_HTTP_ADAPTER_LOG_LEVEL: debug
      MF_HTTP_ADAPTER_PORT: 8185
      MF_NATS_URL: nats://nats:4222
      MF_THINGS_URL: things:8183
    ports:
      - 8185:8185
    networks:
      - tellee-base-net

  es-redis:
    image: redis:5.0-alpine
    container_name: tellee-es-redis
    restart: on-failure
    networks:
      - tellee-base-net
    volumes:
      - tellee-es-redis-volume:/data

  mqtt-redis:
    image: redis:5.0-alpine
    container_name: tellee-mqtt-redis
    restart: on-failure
    networks:
      - tellee-base-net
    volumes:
      - tellee-mqtt-redis-volume:/data

  mqtt-adapter:
    image: rkrikbaev/mqtt:0.8.0
    container_name: tellee-mqtt
    depends_on:
      - things
      - nats
      - mqtt-redis
    restart: on-failure
    environment:
      MF_MQTT_ADAPTER_LOG_LEVEL: debug
      MF_MQTT_INSTANCE_ID: mqtt-adapter-1
      MF_MQTT_ADAPTER_PORT: 1883
      MF_MQTT_ADAPTER_WS_PORT: 8880
      MF_MQTT_ADAPTER_REDIS_HOST: mqtt-redis
      MF_MQTT_ADAPTER_ES_HOST: es-redis
      MF_NATS_URL: nats://nats:4222
      MF_THINGS_URL: things:8183
    ports:
      - 1883:1883
      - 8880:8880
    networks:
      - tellee-base-net

  bootstrap-db:
    image: postgres:10.2-alpine
    container_name: tellee-bootstrap-db
    restart: on-failure
    environment:
      POSTGRES_USER: tellee
      POSTGRES_PASSWORD: tellee
      POSTGRES_DB: bootstrap
    networks:
      - tellee-base-net
    volumes:
      - tellee-bootstrap-db-volume:/var/lib/postgresql/data

  bootstrap:
    image: rkrikbaev/bootstrap:0.8.0
    container_name: tellee-bootstrap
    depends_on:
      - bootstrap-db
    restart: on-failure
    ports:
      - 8200:8200
    environment:
      MF_BOOTSTRAP_LOG_LEVEL: debug
      MF_BOOTSTRAP_DB_HOST: bootstrap-db
      MF_BOOTSTRAP_DB_PORT: 5432
      MF_BOOTSTRAP_DB_USER: tellee
      MF_BOOTSTRAP_DB_PASS: tellee
      MF_BOOTSTRAP_DB: bootstrap
      MF_BOOTSTRAP_DB_SSL_MODE: disable
      MF_BOOTSTRAP_PORT: 8200
      MF_SDK_BASE_URL: http://things:8182
      MF_USERS_URL: tellee-users:8181
      MF_THINGS_ES_URL: es-redis:6379
      MF_BOOTSTRAP_ES_URL: es-redis:6379
    networks:
      - tellee-base-net


  influxdb-reader:
    image: rkrikbaev/influxdb-reader:0.8.0
    container_name: tellee-influxdb-reader
    restart: on-failure
    environment:
      MF_INFLUX_READER_LOG_LEVEL: debug
      MF_THINGS_URL: things:8183
      MF_INFLUX_READER_PORT: 8905
      MF_INFLUX_READER_DB_NAME: tellee
      MF_INFLUX_READER_DB_HOST: tellee-influxdb
      MF_INFLUX_READER_DB_PORT: 8086
      MF_INFLUX_READER_DB_USER: tellee
      MF_INFLUX_READER_DB_PASS: tellee
    ports:
      - 8905:8905
    networks:
      - tellee-base-net

  influxdb:
    image: influxdb:1.6.4-alpine
    container_name: tellee-influxdb
    restart: on-failure
    environment:
      INFLUXDB_DB: tellee
      INFLUXDB_ADMIN_USER: tellee
      INFLUXDB_ADMIN_PASSWORD: tellee
    networks:
      - tellee-base-net
    ports:
      - 8086:8086
    volumes:
      - tellee-influxdb-volume:/var/lib/influxdb

  influxdb-writer:
    image: rkrikbaev/influxdb-writer:0.8.0
    container_name: tellee-influxdb-writer
    depends_on:
      - influxdb
    restart: on-failure
    environment:
      MF_INFLUX_WRITER_LOG_LEVEL: debug
      MF_NATS_URL: nats://nats:4222
      MF_INFLUX_WRITER_PORT: 8900
      MF_INFLUX_WRITER_BATCH_SIZE: 5000
      MF_INFLUX_WRITER_BATCH_TIMEOUT: 5
      MF_INFLUX_WRITER_DB_NAME: tellee
      MF_INFLUX_WRITER_DB_HOST: tellee-influxdb
      MF_INFLUX_WRITER_DB_PORT: 8086
      MF_INFLUX_WRITER_DB_USER: tellee
      MF_INFLUX_WRITER_DB_PASS: tellee
    ports:
      - 8900:8900
    networks:
      - tellee-base-net
    volumes:
      - ./channels.toml:/config/channels.toml

  admin-panel-server:
    container_name: admin-panel-server
    restart: on-failure
    build:
      context: .
      dockerfile: ../../tellee-admin-panel/Dockerfile
      args:
        - MAINFLUX_URL=http://nginx
        - BOOTSTRAP_URL=http://bootstrap:8200
        - UI_URL=http://admin-panel-interface:8000
        - DATABASE_URL=mongodb://admin-panel-db:27017/tellee_admin
    image: rkrikbaev/admin-panel-server
    ports:
      - 5000:5000
    depends_on:
      - admin-panel-db
    links:
      - admin-panel-db
    networks:
      - tellee-base-net
    environment:
      WAIT_HOSTS: admin-panel-db:27017
      DATABASE_URL: mongodb://admin-panel-db:27017/tellee_admin
      MAINFLUX_URL: http://nginx
      BOOTSTRAP_URL: http://bootstrap:8200
      UI_URL: http://admin-panel-interface:8000

  admin-panel-interface:
    container_name: admin-panel-interface
    restart: on-failure
    build:
      context: ../../tellee-admin-panel/client/
      dockerfile: ../../tellee-admin-panel/Dockerfile
      args:
        - REACT_APP_EXPRESS_HOST=http://admin-panel-server:5000
        - REACT_APP_MAINFLUX_USER=zeinetsse3@email.com
        - REACT_APP_CHANNEL_NAME=global_channel
        - FLASK_URL=tellee-ml:8100
    image: rkrikbaev/admin-panel-interface
    ports:
      - 8000:8000
    networks:
      - tellee-base-net
    links:
      - admin-panel-server
    environment:
      REACT_APP_EXPRESS_HOST: http://admin-panel-server:5000
      REACT_APP_MAINFLUX_USER: zeinetsse4@email.com
      REACT_APP_CHANNEL_NAME: global_channel
      FLASK_URL: tellee-ml

  admin-panel-db:
    container_name: admin-panel-mongodb
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod
    networks:
      - tellee-base-net
  
  user-ui:
    container_name: user-ui
    image: rkrikbaev/grafana-with-plugins:latest
    restart: on-failure
    user: "0"
    links:
      - influxdb
    volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - tellee-base-net
      
 # tellee-ml:
 #   container_name: tellee-ml
 #   image: rkrikbaev/telle-ml
 #   restart: on-failure
 #   volumes:
 #     - ../tellee/data:/app/data
 #   ports:
 #     - "3300:3300"
 #   networks:
 #     - tellee-base-net
